spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/crsdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: sku2
    password: Skupw12**
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/db.changelog-master.yaml

logging:
  level:
    root: INFO